// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAgdB-mUAFPhFPv6E4YjoytW8R9Z2zA_M',
    appId: '1:560126287122:web:80aa40ba703b8c31c967cb',
    messagingSenderId: '560126287122',
    projectId: 'flutter-projekt-10cf0',
    authDomain: 'flutter-projekt-10cf0.firebaseapp.com',
    storageBucket: 'flutter-projekt-10cf0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM9uT2MPejcZWxWHUK_PcsZ8EpvP-WxxI',
    appId: '1:560126287122:android:cf939431b934ec04c967cb',
    messagingSenderId: '560126287122',
    projectId: 'flutter-projekt-10cf0',
    storageBucket: 'flutter-projekt-10cf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1LW1T4NdCWEhhxYIE5NshRZO0yaz2xHw',
    appId: '1:560126287122:ios:a6b1a815cb6ef0d2c967cb',
    messagingSenderId: '560126287122',
    projectId: 'flutter-projekt-10cf0',
    storageBucket: 'flutter-projekt-10cf0.appspot.com',
    iosClientId: '560126287122-thpo35dmlv05bcdgklm8o906emaa3orq.apps.googleusercontent.com',
    iosBundleId: 'com.example.projekt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1LW1T4NdCWEhhxYIE5NshRZO0yaz2xHw',
    appId: '1:560126287122:ios:cbe7974e16e3ccaec967cb',
    messagingSenderId: '560126287122',
    projectId: 'flutter-projekt-10cf0',
    storageBucket: 'flutter-projekt-10cf0.appspot.com',
    iosClientId: '560126287122-c2uipgpduevbjvu80jcc70q486r7i975.apps.googleusercontent.com',
    iosBundleId: 'com.example.projekt.RunnerTests',
  );
}
